#!/usr/bin/env bash

# START CONFIGURATION
DOLLAR='$'
export VCW_MODULE_PACKAGES="\
registry:vcwc/registry,\
metrics_monitor:vcwc/elastic/heartbeat"
# END CONFIGURATION

##### START MOULE CONFIGURATION KEYVALUES #####
export MODECO_REGISTRY_PORT="5000"
##### END MOULE CONFIGURATION KEYVALUES #####
