#!/usr/bin/env bash

prefix="vcwc_registry__$1"

if [[ "vcwc_registry__metrics_monitor_heartbeat_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcwc_registry__metrics_monitor_heartbeat_data_volume
fi

if [[ "vcwc_registry__metrics_monitor_heartbeat_monitors_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcwc_registry__metrics_monitor_heartbeat_monitors_volume
fi

if [[ "vcwc_registry__registry_registry_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcwc_registry__registry_registry_data_volume
fi
