---
version: '3'
services:

# START SERVICE vcwc/registry
  registry:
    image: ${VCW_REGISTRY}registry:2
    environment: []
    command: []
    volumes: [${VCW_STACK_STACKPREFIX}_registry_data_volume:/var/lib/registry]
    ports: [${REGISTRY_PORTS}]
    networks: [${VCW_STACK_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${REGISTRY_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${REGISTRY_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${REGISTRY_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/registry

networks: {${VCW_STACK_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_STACKPREFIX}_registry_data_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
