- type: http
  id: external_kafka_connect_endpoint
  name: Kafka Connect External
  hosts: ["http://${VCW_STACK_HOSTNAME}:${MODECO_KAFKA_CONNECT_ENDPOINT_PORT}"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "${VCW_STACK_MODULE_URLPREFIX}"
    stack: kafka_connect
    type: external
    service: kafka_connect
    area: endpoint




- type: http
  id: internal_kafka_connect_endpoint
  name: Kafka Connect Internal
  hosts: ["http://${VCW_STACK_MODULEPREFIX}_kafka_rest_kafka_rest:8083"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "${VCW_STACK_MODULE_URLPREFIX}"
    stack: kafka_connect
    type: internal
    service: kafka_connect
    area: endpoint
