#!/usr/bin/env bash

##### START COMPONENT CONFIGURATION #####
export SOLECO_MODULE="module.blank"
export SOLECO_MODULE_VERSION=""
export VCW_SOLUTON_HIDE_COMPONENT="false"
##### END COMPONENT CONFIGURATION #####
